### ISSUE TITLE
Fuzion sleepnumber fetching isn't passing arguments

### ISSUE THREAD

**Issue by ClayBenson94** [kbickar/asyncsleepiq#15]
![image](https://user-images.githubusercontent.com/15203744/233718399-3ca203f9-0c78-46b0-bf11-502b4825a41a.png)

Per https://github.com/kbickar/asyncsleepiq/pull/13#issuecomment-1513187241, I think we need to be passing "left" or "right" in the args, as right now we're not passing any and I think that results in "FAIL:2" being returned

**Comment by ClayBenson94** [comment]
Additionally, I think we should update to use the `last` value when splitting this result. Not sure why, but my sleep number app shows this, with this API result

![image](https://user-images.githubusercontent.com/15203744/233719247-88ec5a44-f47c-4c99-916d-1a7770d85824.png)

![image](https://user-images.githubusercontent.com/15203744/233719135-e32eb698-8afb-48c0-9d0b-8e7da0654cee.png)

**Comment by kbickar** [comment]
Is this the same case for the "favorite" sleep number?

**Comment by ClayBenson94** [comment]
> Is this the same case for the "favorite" sleep number?

As far as the arg, yes (though we wouldn't need to change anything about how the result it parsed, it's still just `int(result)`

**Comment by ClayBenson94** [comment]
@kbickar I opened https://github.com/kbickar/asyncsleepiq/pull/16 for this! I might have to lean on you as far as pushing the update to pip/Homeassistant, though!

**Comment by kbickar** [comment]
Thanks! Created https://github.com/kbickar/asyncsleepiq/releases/tag/v1.3.4 
Should be on pypi in a couple minutes
