### ISSUE TITLE
Footwarmer Control

### ISSUE THREAD

**Issue by capritzl** [kbickar/asyncsleepiq#17]
Hubitat has control of the SleepIQ footwarmers in its integration.  I would be willing to test a HA integration that has control of footwarmers entities.

**Comment by kbickar** [comment]
I looked briefly at the Hubitat app  but I'm not so familiar with the architecture.  Are you able to get the API endpoints and calls that it requires

**Comment by capritzl** [comment]
I am not familiar with the API endpoints. I will need to do some research. What information are you specifically looking for?

**Comment by capritzl** [comment]
It does not look like they documented the API.  I see a number of people referencing a lack of API documentation.

This is the code I use:

https://raw.github.com/rvrolyk/SleepNumberController/master/SleepNumberController_App.groovy

Attached find a screen print of the hubitat device status.



Charles
________________________________

**Comment by capritzl** [comment]
Have you had time to take a look at the integration?

Charles
________________________________

**Comment by kbickar** [comment]
Added with #18

**Comment by capritzl** [comment]
@kbickar - how can I help with testing?

**Comment by kbickar** [comment]
You could try out v1.4.0 manually to see if it works for you or I think @dzader will be updating the HomeAssistant integration soon with the new version/functionality

**Comment by dzader** [comment]
I probably wont be able to work on getting this PR ready to actually submit but if you copy the sleepiq component from my fork https://github.com/home-assistant/core/tree/dev/homeassistant/components/sleepiq into `config/custom_components/` it should give you working controls of the temperature and timers for both foot warmers

**Comment by kbickar** [comment]
I submitted a PR based on dzader's code to HA: https://github.com/home-assistant/core/pull/105931

**Comment by capritzl** [comment]
Is there a way to send you a small donation to you for adding the foot warmer support?

Charles
________________________________
