### ISSUE TITLE
Add better light support

### ISSUE THREAD

**Issue by kbickar** [kbickar/asyncsleepiq#2]
Thanks for the foundation changes @mfugate1  Mine doesn't have/support the foundation so I find it a little difficult to test it - does yours have the lights? If so, can you test the following code at the end of the example:
```
    print("Available lights:")
    for light in bed.foundation.lights:
        print(f" - {light}: {bed.foundation.lights[light]}")
        
    print("Turning on lights...")
    for light in bed.foundation.lights:
        bed.foundation.set_light(light, True)
        bed.foundation.fetch_light(light)
        print(f" {light}: {bed.foundation.lights[light]}")
        await asyncio.sleep(1)
    await asyncio.sleep(10)
    print("Turning off lights...")
    for light in bed.foundation.lights:
        bed.foundation.set_light(light, False)
        bed.foundation.fetch_light(light)
        print(f" {light}: {bed.foundation.lights[light]}")
        await asyncio.sleep(1)

    status = await bed.foundation.foundation_status()
    print(f"Foundation status: {status}")
    print(f"Features: {bed.foundation.features}")
```
If the above works, it would be good to create a new light object which could then be more easily referenced to turn on/off

**Comment by mfugate1** [comment]
I have a foundation with an under bed light and adjustable head and foot (but not a split head).

It correctly finds that I have one light available, but the set_light() call is returning a 400. That call still works in the old sleepyq library, but I haven't been able to find the reason it isn't working here yet.

**Comment by mfugate1** [comment]
Fixed in #3 

The sleepiq api wants json data for those PUT calls.

**Comment by mfugate1** [comment]
I'm adding a new Actuator object in preparation for adding a number entity to Home Assistant to control foundation position. I will do the same for light.

**Comment by kbickar** [comment]
Sounds good

**Comment by kbickar** [comment]
Added in #4
