### ISSUE TITLE
Feature Request: Climate Controls for Climate360 Bed

### ISSUE THREAD

**Issue by jmwaldrip** [kbickar/asyncsleepiq#20]
I would like to add support for the cooling/warming functionality of the Cloud360 bed within the library to be utilized with Home Assistant. 

I am willing to contribute development time and testing time if this is a feature you're willing to add to the library. 

Thank you!

**Comment by jmwaldrip** [comment]
Submitted #22  adding support for the Heidi climate system.

**Comment by jmwaldrip** [comment]
Submitted a bug fix for foot warmers and core climate update calls. #23 

TLDR: The object was never updated after a setting change or during update calls due to the update call not being fully implemented.

**Comment by kbickar** [comment]
Added in #22
