### ISSUE TITLE
Foot Warmer Time Range

### ISSUE THREAD

**Issue by jmwaldrip** [kbickar/asyncsleepiq#21]
Hey there! 

I noticed in fuzion/foot_warmer.py and foot_warmer.py that the time range is limited to 360 minutes (6 hours), but the app will allow you to set it to 600 minutes (10 hours). 

```
        if time <= 0 or time > 360:
            raise ValueError("Invalid Time, must be between 0 and 360")
```

I am curious if that is on purpose?

**Comment by kbickar** [comment]
That's a value @dzader picked.  I don't know if it's different for some models or not, but it could be bumped up at least for the fuzion ones

**Comment by dzader** [comment]
On my i8 the app only lets you select up to 6 hours (although I never tested with larger values) which is where I got that value! Seems like updating the fuzion version makes sense!

**Comment by jmwaldrip** [comment]
I think it would be fine either way. The app lets me go to 10 hours, maybe its a difference in model? That's weird. 

If y'all want, I can update it in #22.

**Comment by kbickar** [comment]
I updated it to 600 in the fuzion class and created the variable `max_foot_warming_time` that can be referenced to get the limit
