### ISSUE TITLE
No sensor for left side lower foundation settings

### ISSUE THREAD

**Issue by kartcon** [kbickar/asyncsleepiq#27]
Until recently, I had no interest in adjusting the base foot position. Now r that I want to make these adjustments I’ve noticed that I have a sensor for (SleepNumber I8 Right Foot Position) but no corresponding LEFT foot position. 
For all other controls there are separate sensors for both sides, just not the foot position. I hope you can address this in the near future. Thanks for an otherwise great integration in Home Assistant.
Running Home Assistant 2024.8.1 on RPi4 w SSD
All components are latest available public release. No beta apps installed.
I’d be happy to supply any information you may need to further the process.
Thanks,
Art
aka Kartcon on the forums

**Comment by kbickar** [comment]
Which model bed do you have?

It looks like the "splitHead" type has only one foot actuator and two head actuators.

**Comment by kartcon** [comment]
Keilin,

Well you are correct! Even though we have individual controls in the SleepNumber app, there is only one actuator for the foot position. That’s a bit disappointing as I thought we had individual control, but that’s not anything you can fix. I do appreciate the quick response and the mini education into what we bought vs what we thought we bought!!! Thanks again for a great app and all the work it takes to answer these questions.

Art
